# -*- coding: utf-8 -*-
"""Imersao-Python-Aula02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uSyUuU67jJ7s6ccsNpkk8hTabx1gUp2z

# Aula 2 da Imersão Python: Do Excel à Análise de Dados
> #### Instituição: Alura  
> #### Objetivo: manipulação de dados com Python Pandas
> #### Autora: Carla Edila Silveira
> #### Data: 26/03/2024

><img src='https://i.postimg.cc/PJKTsD4R/aula02-cabecalho.png'>
"""

# Importa biblioteca Pandas do Python

import pandas as pd

# Criada variavel para receber a leitura da aba Principal da planilha acoes-pura.xlsx
df_principal = pd.read_excel("/content/acoes-pura.xlsx", sheet_name="Principal")
df_principal

# Criada variavel para receber a leitura da aba Gotal_deacoes da planilha acoes-pura.xlsx
df_total_acoes = pd.read_excel("/content/acoes-pura.xlsx", sheet_name="Total_de_acoes")
df_total_acoes

# Criada variavel para receber a leitura da aba Ticker da planilha acoes-pura.xlsx
df_ticker = pd.read_excel("/content/acoes-pura.xlsx", sheet_name="Ticker")
df_ticker

# Criada variavel para receber a leitura da aba ChatGPT da planilha acoes-pura.xlsx
df_chatgpt = pd.read_excel("/content/acoes-pura.xlsx", sheet_name="ChatGPT")
df_chatgpt